apiVersion: "melo.k8s.do/v1"
kind: OpenGauss
metadata:
  name: test-opengauss
spec:
  image: opengauss:debug
  imagePullPolicy: IfNotPresent
  opengauss:
    master:
      replicas: 1
    worker:
      replicas: 0