apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: opengausses.melo.k8s.do
spec:
  group: melo.k8s.do
  names:
    kind: OpenGauss
    listKind: OpenGaussList
    plural: opengausses
    singular: opengauss
    shortNames:
    - og
    categories:
    - all
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: {}
    additionalPrinterColumns:
    # - jsonPath:  .status.conditions[?(@.type=="Ready")].status
    #   name: Ready
    #   type: string
    - jsonPath: .spec.image
      description: The image for opengauss cluster.
      name: Image
      type: string
    - jsonPath: .status.readyMaster
      description: The ready master number of opengauss cluster
      name: Master-Ready
      type: string
    - jsonPath: .spec.opengauss.master
      description: The desired master number of opengauss cluster
      name: Master-Desire
      type: integer
    - jsonPath: .status.readyReplicas
      description: The ready replicas number of opengauss cluster
      name: Replicas-Ready
      type: string
    - jsonPath: .spec.opengauss.replicas
      description: The desired replicas number of opengauss cluster
      name: Replicas-Desire
      type: integer
    - jsonPath: .status.opengaussStatus
      name: Status
      type: string
      description: Current sync status of opengauss resource
    schema:
      openAPIV3Schema:
        type: object
        required:
          - kind
          - apiVersion
          - spec
        properties:
          kind:
            type: string
            enum:
              - OpenGauss
          apiVersion:
            type: string
            enum:
              - melo.k8s.do/v1
          spec:
            type: object
            required:
              - image
              - opengauss
            properties:
              image:
                type: string
              imagePullPolicy:
                type: string
              opengauss:
                type: object
                required:
                  - master
                  - replicas
                properties:
                  master:
                    format: int32
                    type: integer
                    minimum: 1
                  replicas:
                    format: int32
                    type: integer
                    minimum: 0
              resources:
                type: object
                required:
                  - requests
                  - limits
                properties:
                  limits:
                    type: object
                    required:
                      - cpu
                      - memory
                    properties:
                      cpu:
                        type: string
                        # Decimal natural followed by m, or decimal natural followed by
                        # dot followed by up to three decimal digits.
                        #
                        # This is because the Kubernetes CPU resource has millis as the
                        # maximum precision.  The actual values are checked in code
                        # because the regular expression would be huge and horrible and
                        # not very helpful in validation error messages; this one checks
                        # only the format of the given number.
                        #
                        # https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu
                        pattern: '^(\d+m|\d+(\.\d{1,3})?)$'
                        # Note: the value specified here must not be zero or be lower
                        # than the corresponding request.
                      memory:
                        type: string
                        # You can express memory as a plain integer or as a fixed-point
                        # integer using one of these suffixes: E, P, T, G, M, k. You can
                        # also use the power-of-two equivalents: Ei, Pi, Ti, Gi, Mi, Ki
                        #
                        # https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory
                        pattern: '^(\d+(e\d+)?|\d+(\.\d+)?(e\d+)?[EPTGMK]i?)$'
                        # Note: the value specified here must not be zero or be higher
                        # than the corresponding limit.
                  requests:
                    type: object
                    required:
                      - cpu
                      - memory
                    properties:
                      cpu:
                        type: string
                        pattern: '^(\d+m|\d+(\.\d{1,3})?)$'
                      memory:
                        type: string
                        pattern: '^(\d+(e\d+)?|\d+(\.\d+)?(e\d+)?[EPTGMK]i?)$'
          status:
            type: object
            additionalProperties:
              type: string