apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: opengauss-operator
  name: opengauss-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opengauss-operator
rules:
- apiGroups: ["controller.k8s.do"]
  resources: ["opengausses", "opengausses/status", "opengausses/spec"]
  verbs: ["create", "list", "delete", "update", "deletecollection", "get"]
  # resourceNames: ["admin","edit","view"]
- apiGroups: [""]
  resources: ["secrets", "services", "persistentvolumeclaims", "persistentvolumes", "pods", "configmaps", "events"]
  verbs: ["create", "list", "delete", "update", "get", patch]
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["create", "list", "delete", "update", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: opengauss-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: opengauss-operator
subjects:
- kind: ServiceAccount
  name: opengauss-operator
  namespace: default