apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: opengauss-csi
provisioner: lvmplugin.csi.alibabacloud.com
parameters:
    vgName: opengauss
    fsType: ext4
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true