name: go build

on:
  push:
    branches:
    - master
  pull_request:
    branches: 
    - master

jobs:

  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
  
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 
    - name: Build
      run: go build -v -o controller .
